### ISSUE TITLE
How to customize cards style

### ISSUE THREAD

**Issue by FrazCake** [nukeop/react-ui-cards#22]
Hi, thank you for this amazing library!
I'm a beginner and I'm wondering if it's possible to change the cards size and other css properties without changing the scss sources.
If it is possible is there a recommended way to do it?
Thank you.

**Comment by nukeop** [comment]
Hi, I'm glad you've found this useful.
There is cardClass in some (but not all) cards that can be used to apply additional classes.
If you're interested, I might update the code to ensure that classNames and style are passed down to all cards, or you could create a pull request with some changes if you'd like to do it this way.
