### ISSUE TITLE
How do i add data into the CryptoCards?

### ISSUE THREAD

**Issue by archivecoderzero** [nukeop/react-ui-cards#24]
I am trying to figure out how to add a data from the Coin Market Cap API into CryptoCard ,

**Comment by nukeop** [comment]
You can take a look at the demo:
https://github.com/nukeop/react-ui-cards/blob/master/demo/index.jsx#L305

All you need is an array of numbers.

**Comment by archivecoderzero** [comment]
Awesome! Thank you !
