### ISSUE TITLE
Gives Error: ReferenceError: window is not defined     at (..../node_modules/react-ui-cards/bundle.js:27:5640)

### ISSUE THREAD

**Issue by jermsam** [nukeop/react-ui-cards#25]
Looks like it has no support for Server Side Rendering. When used in a Next.js project, it gives the highlighted error. Is this something you can fix?

**Comment by nukeop** [comment]
Hm, I didn't think about server side rendering when creating this, so it might not be easy to fix. Maybe it needs a webpack config tweak.

**Comment by ignacioaraya1995** [comment]
How can we solve it?

**Comment by nukeop** [comment]
Not sure if it still occurs, I've rewritten everything from scratch since then.
