### ISSUE TITLE
Getting Error while using the card components

### ISSUE THREAD

**Issue by AzizMsaddek** [nukeop/react-ui-cards#30]
I installed the package and tried to use the Product component, but I got an error:
https://i.imgur.com/im6SfJP.png

This is my code:

import React, { Component } from 'react';
import ProductCard from 'react-ui-cards';

export default class SpecialProducts extends Component {
	
	render() {
		return (
			<div>
				<ProductCard productName="test" price="200" />
			</div>
		);
	}
}

**Comment by nukeop** [comment]
This is a problem with the way you're exporting this component and importing it somewhere else, not with the cards.

**Comment by AzizMsaddek** [comment]
> You're importing the card wrong, the default export from `react-ui-cards` contains an object with individual card components, from which you can get your card.

Thank you for your repy, can you please give me the right importation ? Beacause I have read the documentation but I didn't find the right way to do it.

**Comment by AzizMsaddek** [comment]
I managed to solve the problem, thank you for your great work, keep it up!
