### ISSUE TITLE
Add "target" attribute to anchor tag in NewsHeaderCard

### ISSUE THREAD

**Issue by RiteshKSingh1709** [nukeop/react-ui-cards#48]
- Can give flexibility to add target attribute to anchor tag in NewsHeaderCapCard.
![image](https://user-images.githubusercontent.com/10517315/190989513-10d0ba78-1556-42eb-9aad-af2cd312b20d.png)

**Comment by nukeop** [comment]
Please open a pull request with these changes

**Comment by RiteshKSingh1709** [comment]
thanks for adding me as contributor :-)

**Comment by RiteshKSingh1709** [comment]
PR has been merged hence closing this issue.
