### ISSUE TITLE
needs a key prop, when using fetch axios data and creating an array of objects cant add key

### ISSUE THREAD

**Issue by nikhilsurfingaus** [nukeop/react-ui-cards#63]

**Comment by nikhilsurfingaus** [comment]
`import React from 'react'
import { UserCard } from 'react-ui-cards';
import './InstallMain.css'
import { useEffect , useState} from 'react';
import axios from 'axios';


function InstalllMain() {

    const [stat, setStats] = useState([{}])

    useEffect(() => {
        async function fetchData() {
            const result = await axios(
                'https://api.github.com/users/nikhilsurfingaus',
            );
            const arr = result.data
            const test = [{
                        key: '1',
                        name: 'Followers',
                        value: arr.followers,
                    },
                    {
                        key: '2',
                        name: 'Following',
                        value: arr.following,
                    },
                    {
                        key: '3',
                        name: 'Repos',
                        value: arr.public_repos,
                    },   
                ]
                setStats(test)

          }
          fetchData();

      }, []);


  return (
    <>   
        <div className="head">
            <h1>Install Program Guide</h1>
        </div>
        <div className="prof">
            <UserCard
                float
                header='https://i.imgur.com/vRAtM3i.jpg'
                avatar='https://i.imgur.com/XJxqvsU.jpg'
                name='Nikhil Naik'
                positionName='Github Profile'
                stats={stat}
                key={stat}
            />
      </div>
    </>
  )
}

export default InstalllMain`

**Comment by nikhilsurfingaus** [comment]
Needs key for the list of objects?

**Comment by nukeop** [comment]
You can put a key directly on any React markup. It doesn't have to be added to the component (and in fact shouldn't be).

**Comment by nikhilsurfingaus** [comment]
Where would i put a key here to resolve the error:
`
    react-jsx-runtime.development.js:117 Warning: Each child in a list should have a unique "key" prop.

    Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
    at div
`

**Comment by nikhilsurfingaus** [comment]
I tried doing this but it breaks code
`
        {stat.map((a, i) => (

            <UserCard

            float

            header='https://i.imgur.com/vRAtM3i.jpg'

            avatar='https://i.imgur.com/XJxqvsU.jpg'

            name='Nikhil Naik'

            positionName='Github Profile'

            stats={a}

            key={i}

            />
        ))}
`

**Comment by nikhilsurfingaus** [comment]
So how can i fix this key warning issue?

**Comment by nukeop** [comment]
https://reactjs.org/docs/lists-and-keys.html

**Comment by nikhilsurfingaus** [comment]
Is the key issue because each item in the stat array is used for the stats prop, and usercard needs a key or does the div need a key?
